name: CI

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

defaults:
  run:
    shell: bash
#     working-directory: scripts

jobs:
  build-ubuntu-success:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Fail test
        run: |
          curl https://example.com/

  build-ubuntu-failure:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Fail test
        run: |
          curl https://dfgjndrgierngiergnregerg
          curl https://example.com/

  build-windows-success:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Fail test
        run: |
          curl https://example.com/

  build-windows-failure-bug:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Fail test
        run: |
          curl https://dfgjndrgierngiergnregerg
          curl https://example.com/

  build-windows-failure-bug-bash:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Fail test
        shell: bash
        run: |
          curl https://dfgjndrgierngiergnregerg
          curl https://example.com/

  build-windows-failure-bug-sh:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Fail test
        shell: sh
        run: |
          curl https://dfgjndrgierngiergnregerg
          curl https://example.com/

  build-windows-failure-bug-powershell:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Fail test
        shell: powershell
        run: |
          curl https://dfgjndrgierngiergnregerg
          curl https://example.com/

  build-windows-failure-bug-pwsh:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Fail test
        shell: pwsh
        run: |
          $ErrorActionPreference = 'stop'
          curl https://dfgjndrgierngiergnregerg
          curl https://example.com/

  build-windows-failure-bug-cmd:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Fail test
        shell: cmd
        run: |
          curl https://dfgjndrgierngiergnregerg
          curl https://example.com/
